/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kopnustestisochannel;

import org.jpos.iso.*;

/**
 *
 * @author mohamad
 */
public class KopnusPackager extends ISOBasePackager {
    public KopnusPackager() {
		setFieldPackager(new ISOFieldPackager[] {
				/* 000 */new IFA_NUMERIC(4, "Message Type Indicator"),
				/* 001 */new IFA_BITMAP(64, "Bitmap"),
				/* 002 */new IFA_LLCHAR(19, "Primary Account Number"),
				/* 003 */new IFA_NUMERIC(6, "Processing Code"),
				/* 004 */new IFA_NUMERIC(12, "Transaction amount"),
				/* 005 */new IFA_NUMERIC(12, "Transaction amount"),
				/* 006 */new IFA_NUMERIC(12, "Transaction amount"),
				/* 007 */new IFA_NUMERIC(10, "Transaction date and time"),
				/* 008 */new IFA_NUMERIC(10, "Transaction date and time"),
				/* 009 */new IFA_NUMERIC(10, "Transaction date and time"),
				/* 010 */new IFA_NUMERIC(10, "Transaction date and time"),
				/* 011 */new IFA_NUMERIC(6, "Sytem Trace Audit Number"),
                                /* 012 */new IFA_NUMERIC(6 , "Transaction time"),
                                /* 013 */new IFA_NUMERIC(4 , "Transaction date"),
                                /* 014 */new IFA_NUMERIC(4 , "Transaction date"),
                                /* 015 */new IFA_NUMERIC(4 , "Settlement date"),
                                /* 016 */new IFA_NUMERIC(4 , "Settlement date"),
                                /* 017 */new IFA_NUMERIC(4 , "Settlement date"),
                                /* 018 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 019 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 020 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 021 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 022 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 023 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 024 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 025 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 026 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 027 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 028 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 029 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 030 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 031 */new IFA_NUMERIC(4 , "Merchant type / Jenis Kanal Distribusi"),
                                /* 032 */new IFA_LLCHAR(11 , "Collecting agent/Acquirer code"),
                                /* 033 */new IFA_LLCHAR(11 , "Collecting agent/Acquirer code"),
                                /* 034 */new IFA_LLCHAR(11 , "Collecting agent/Acquirer code"),
                                /* 035 */new IFA_LLCHAR(11 , "Collecting agent/Acquirer code"),
                                /* 036 */new IFA_LLCHAR(11 , "Collecting agent/Acquirer code"),
                                /* 037 */new IFA_NUMERIC(12 , "Retrieval Reference Number"),
                                /* 038 */new IFA_NUMERIC(12 , "Retrieval Reference Number"),
                                /* 039 */new IF_CHAR(2 , "Response Code"),
                                /* 040 */new IF_CHAR(2 , "Response Code"),
                                /* 041 */new IFA_NUMERIC(8 , "Terminal Id"),
                                /* 042 */new IFA_NUMERIC(15 , "Card acceptor identification code"),
                                /* 043 */new IFA_NUMERIC(15 , "Card acceptor identification code"),
                                /* 044 */new IFA_NUMERIC(15 , "Card acceptor identification code"),
                                /* 045 */new IFA_NUMERIC(15 , "Card acceptor identification code"),
                                /* 046 */new IFA_NUMERIC(15 , "Card acceptor identification code"),
                                /* 047 */new IFA_NUMERIC(15 , "Card acceptor identification code"),
                                /* 048 */new IFA_LLLCHAR(999 , "Additonal data"),
                                /* 049 */new IFA_NUMERIC(3 , "Currency code"),
                                /* 050 */new IFA_NUMERIC(3 , "Currency code"),
                                /* 051 */new IFA_NUMERIC(3 , "Currency code"),
                                /* 052 */new IF_CHAR(16 , "PIN"),
                                /* 053 */new IF_CHAR(16 , "PIN"),
                                /* 054 */new IF_CHAR(16 , "PIN"),
                                /* 055 */new IF_CHAR(16 , "PIN"),
                                /* 056 */new IF_CHAR(16 , "PIN"),
                                /* 057 */new IF_CHAR(16 , "PIN"),
                                /* 058 */new IF_CHAR(16 , "PIN"),
                                /* 059 */new IF_CHAR(16 , "PIN"),
                                /* 060 */new IF_CHAR(16 , "PIN"),
                                /* 061 */new IFA_LLLCHAR(999 , "Private data 1"),
                                /* 062 */new IFA_LLLCHAR(999 , "Private data 2"),
                                /* 063 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 064 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 065 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 066 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 067 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 068 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 069 */new IFA_LLLNUM(3 , "Institution code"),
                                /* 070 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 071 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 072 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 073 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 074 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 075 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 076 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 077 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 078 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 079 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 080 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 081 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 082 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 083 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 084 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 085 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 086 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 087 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 088 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 089 */new IFA_NUMERIC(3 , "Kode informasi untuk network management"),
                                /* 090 */new IFA_NUMERIC(42 , "Original Transaction Data"),
                                /* 091 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 092 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 093 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 094 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 095 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 096 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 097 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 098 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 099 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 100 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 101 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 102 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 103 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 104 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 105 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 106 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 107 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 108 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 109 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 110 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 111 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 112 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 113 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 114 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 115 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 116 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 117 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 118 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 119 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 120 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 121 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 122 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 123 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 124 */ new IFA_NUMERIC(42, "Original Transaction Data"),
				/* 125 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 126 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 127 */new IFA_NUMERIC(42 , "Original Transaction Data"),
				/* 128 */new IFA_NUMERIC(42 , "Original Transaction Data"),
		});
	}

}
